name: insta_assets_picker_demo
description: The demo project for the insta_assets_picker package.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.3.0-dev.3

environment:
  sdk: ^3.2.0
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  insta_assets_picker:
    path: ../

  # for camera examples
  path: ^1.8.3
  camera: ^0.10.5+9
  wechat_camera_picker: ^4.2.0-dev.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true