name: insta_assets_picker_demo
description: The demo project for the insta_assets_picker package.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.2.0

environment:
  sdk: '>=3.1.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  insta_assets_picker:
    path: ../

  # for camera examples
  path: ^1.8.3
  camera: ^0.10.5+5
  wechat_camera_picker: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true