name: insta_assets_picker_demo
description: The demo project for the insta_assets_picker package.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 3.4.0

environment:
  sdk: ^3.4.0
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  insta_assets_picker:
    path: ../

  # for camera examples
  camera: ^0.10.0
  wechat_camera_picker: ^4.3.7

  # for video examples
  # ffmpeg_kit_flutter_min: ^6.0.3
  mime: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true