name: insta_assets_picker
description: An image picker similar with Instagram, supports multi picking, crop and aspect ratio.
version: 1.5.1
repository: https://github.com/LeGoffMael/insta_assets_picker

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  insta_assets_crop: ^0.0.2 # custom package from image_crop
  fraction: ^5.0.0 # to show crop ratio in crop view
  wechat_assets_picker: ^8.5.0
  provider: ^6.0.5 # match with wechat_assets_picker package
  extended_image: ^8.0.1 # match with wechat_assets_picker package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

screenshots:
  - description: 'Scroll animation'
    path: example/screenshots/scroll.webp
  - description: 'Crop & export'
    path: example/screenshots/crop-export.webp