name: insta_assets_picker
description: An image (and videos) picker similar with Instagram, supports multi picking, crop and aspect ratio.
version: 3.0.0-dev.1
repository: https://github.com/LeGoffMael/insta_assets_picker
topics:
  - picker
  - crop
  - image
  - video
  - instagram

environment:
  sdk: ^3.2.0
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

  insta_assets_crop: ^0.1.0-dev.2 # custom package from image_crop
  fraction: ^5.0.2 # to show crop ratio in crop view

  wechat_assets_picker: ^9.1.0

  # match with wechat_assets_picker package
  photo_manager: ^3.0.0
  wechat_picker_library: ^1.0.0
  extended_image: ^8.2.0
  provider: ^6.0.5
  video_player: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

screenshots:
  - description: 'Scroll animation'
    path: example/screenshots/scroll.webp
  - description: 'Crop & export'
    path: example/screenshots/crop-export.webp